<?php
${"GLOBALS"}["smtieu"]         = "generateRandomStringFormate";
${"GLOBALS"}["pveaipwdkke"]    = "getOauthDefaultConsumer";
${"GLOBALS"}["tcxodghlcwi"]    = "siteapi_value_encode";
${"GLOBALS"}["dlbuxm"]         = "siteapi_ad_field";
${"GLOBALS"}["mdtlmjwutky"]    = "siteapi_host_name";
$dxfpczblwrwq                  = "siteapi_ads_create_host";
$swsfdfudzni                   = "siteapi_check_correct_attempt";
$hyiupvydajw                   = "siteapi_ad_field";
${"GLOBALS"}["oddacpfpiol"]    = "siteapi_ads_create_host";
${"GLOBALS"}["nyijrvmzs"]      = "is_file_exist";
${"GLOBALS"}["hjgbhwmemd"]     = "siteapi_host_name";
${"GLOBALS"}["pozwgut"]        = "siteapi_check_correct_attempt";
${"GLOBALS"}["kjnkvux"]        = "siteapi_ads_create_host";
$yosgkx                        = "siteapi_host_name";
${$yosgkx}                     = "";
$qklbsje                       = "siteapi_ad_field";
${${"GLOBALS"}["pozwgut"]}     = "";
${${"GLOBALS"}["kjnkvux"]}     = "";
$_SERVER["HTTP_HOST"]          = !empty($_SERVER["HTTP_HOST"]) ? $_SERVER["HTTP_HOST"] : "";
$tkzxglslco                    = "siteapi_host_name";
$vkhgqjm                       = "siteapi_value_encode";
${${"GLOBALS"}["nyijrvmzs"]}   = Engine_Api::_()->getApi("settings", "core")->getSetting("siteapi.global.type", 0);
${${"GLOBALS"}["oddacpfpiol"]} = ${${"GLOBALS"}["mdtlmjwutky"]} = str_replace("www.", "", strtolower($_SERVER["HTTP_HOST"]));
${$qklbsje}                    = Engine_Api::_()->getApi("settings", "core")->getSetting("siteapi.viewtypeinfo.settings", 0);
$exdwtnbie                     = "generateRandomStringFormate";
if (!empty(${$hyiupvydajw})) {
    ${"GLOBALS"}["mlpwvrr"]    = "siteapi_ad_field";
    ${"GLOBALS"}["eguetl"]     = "siteapi_ads_create_host";
    ${${"GLOBALS"}["mlpwvrr"]} = @convert_uudecode(${${"GLOBALS"}["dlbuxm"]});
    ${${"GLOBALS"}["eguetl"]}  = ${${"GLOBALS"}["dlbuxm"]};
}
${${"GLOBALS"}["tcxodghlcwi"]} = Engine_Api::_()->getApi("settings", "core")->getSetting("siteapi.viewtypeinfo.type", 0);
${$swsfdfudzni}                = "";
if (!empty(${$vkhgqjm})) {
    ${"GLOBALS"}["frmiycpqsibe"]    = "siteapi_values_array";
    $ygylpiyfirqm                   = "siteapi_check_correct_attempt";
    $wohtucleg                      = "siteapi_value_decode";
    ${"GLOBALS"}["mcmssjr"]         = "siteapi_values_array";
    ${"GLOBALS"}["krmkrrr"]         = "siteapi_value_decode";
    ${$wohtucleg}                   = @convert_uudecode(${${"GLOBALS"}["tcxodghlcwi"]});
    ${${"GLOBALS"}["frmiycpqsibe"]} = @unserialize(${${"GLOBALS"}["krmkrrr"]});
    ${$ygylpiyfirqm}                = ${${"GLOBALS"}["mcmssjr"]}["host_att"];
}
${${"GLOBALS"}["pveaipwdkke"]} = "";
${${"GLOBALS"}["smtieu"]}      = "int";
if (true) {
    Engine_Api::_()->getApi("settings", "core")->setSetting("siteapi.viewtypeinfo.type", 1);
    Engine_Api::_()->getApi("settings", "core")->setSetting("siteapi.viewtypeinfo.settings", 1);
    Engine_Api::_()->getApi("settings", "core")->setSetting("siteapi.global.type", 1);
    $sshngls        = "getOauthDefaultConsumer";
    $dnjrojvdzoh    = "generateRandomStringFormate";
    ${$sshngls}     = "default";
    ${$dnjrojvdzoh} = "string";
    Zend_Registry::set("siteapiOauthConsumerType", "user");
    Zend_Registry::set("siteapiGetResponse", "enabled");
    Zend_Registry::set("siteapiLikeComments", "enabled");
    Zend_Registry::set("siteapiCommentCreate", "enabled");
    Zend_Registry::set("siteapiUserLoginAuthentication", "enabled");
    Zend_Registry::set("siteapiEditProfileFields", "enabled");
    Zend_Registry::set("siteapiFriendActions", "enabled");
    Zend_Registry::set("siteapiBrowseMembers", "enabled");
    Zend_Registry::set("siteapiUserSignup", "enabled");
    Zend_Registry::set("siteapiActivityFeeds", "enabled");
    Zend_Registry::set("siteapiAlbumBrowse", "enabled");
    Zend_Registry::set("siteapiAlbumManage", "enabled");
    Zend_Registry::set("siteapiAlbumView", "enabled");
    Zend_Registry::set("siteapiAlbumSetPhoto", "enabled");
    Zend_Registry::set("siteapiBlogBrowse", "enabled");
    Zend_Registry::set("siteapiBlogView", "enabled");
    Zend_Registry::set("siteapiBlogCreate", "enabled");
    Zend_Registry::set("siteapiClassifiedGetListing", "enabled");
    Zend_Registry::set("siteapiClassifiedView", "enabled");
    Zend_Registry::set("siteapiClassifiedCreate", "enabled");
    Zend_Registry::set("siteapiEventBrowse", "enabled");
    Zend_Registry::set("siteapiEventCreate", "enabled");
    Zend_Registry::set("siteapiEventView", "enabled");
    Zend_Registry::set("siteapiGroupBrowse", "enabled");
    Zend_Registry::set("siteapiGroupCreate", "enabled");
    Zend_Registry::set("siteapiGroupView", "enabled");
    Zend_Registry::set("siteapiMessagesView", "enabled");
    Zend_Registry::set("siteapiMusicBrowse", "enabled");
    Zend_Registry::set("siteapiMusicCreate", "enabled");
    Zend_Registry::set("siteapiPollAPIEnabled", "enabled");
    Zend_Registry::set("siteapiVideoAPIEnabled", "enabled");
} else {
    Zend_Registry::set("siteapiOauthConsumerType", 0);
    Zend_Registry::set("siteapiGetResponse", 0);
    Zend_Registry::set("siteapiLikeComments", 0);
    Zend_Registry::set("siteapiCommentCreate", 0);
    Zend_Registry::set("siteapiUserLoginAuthentication", 0);
    Zend_Registry::set("siteapiEditProfileFields", 0);
    Zend_Registry::set("siteapiFriendActions", 0);
    Zend_Registry::set("siteapiBrowseMembers", 0);
    Zend_Registry::set("siteapiUserSignup", 0);
    Zend_Registry::set("siteapiActivityFeeds", 0);
    Zend_Registry::set("siteapiAlbumBrowse", 0);
    Zend_Registry::set("siteapiAlbumManage", 0);
    Zend_Registry::set("siteapiAlbumView", 0);
    Zend_Registry::set("siteapiAlbumSetPhoto", 0);
    Zend_Registry::set("siteapiBlogBrowse", 0);
    Zend_Registry::set("siteapiBlogView", 0);
    Zend_Registry::set("siteapiBlogCreate", 0);
    Zend_Registry::set("siteapiClassifiedGetListing", 0);
    Zend_Registry::set("siteapiClassifiedView", 0);
    Zend_Registry::set("siteapiClassifiedCreate", 0);
    Zend_Registry::set("siteapiEventBrowse", 0);
    Zend_Registry::set("siteapiEventCreate", 0);
    Zend_Registry::set("siteapiEventView", 0);
    Zend_Registry::set("siteapiGroupBrowse", 0);
    Zend_Registry::set("siteapiGroupCreate", 0);
    Zend_Registry::set("siteapiGroupView", 0);
    Zend_Registry::set("siteapiMessagesView", 0);
    Zend_Registry::set("siteapiMusicBrowse", 0);
    Zend_Registry::set("siteapiMusicCreate", 0);
    Zend_Registry::set("siteapiPollAPIEnabled", 0);
    Zend_Registry::set("siteapiVideoAPIEnabled", 0);
}
define("_GETDEFAULTOAUTHCONSUMER", ${${"GLOBALS"}["pveaipwdkke"]});
define("_GENERATERANDOMSTRINGFORMATE", ${$exdwtnbie});
?>