<?php $db = Engine_Db_Table::getDefaultAdapter(); 
$db->query('INSERT IGNORE INTO `engine4_core_menuitems` (`id`, `name`, `module`, `label`, `plugin`, `params`, `menu`, `submenu`, `enabled`, `custom`, `order`) VALUES 
(NULL, "sitelogin_admin_main_integration_google", "sitelogin", "Google Integration", NULL, \'{"route":"admin_default","module":"sitelogin","controller":"settings","action":"google"}\', "sitelogin_admin_main_integration", NULL, "1", "0", "3"),
(NULL, "sitelogin_admin_main_integration_linkedin", "sitelogin", "Linkedin Integration", NULL, \'{"route":"admin_default","module":"sitelogin","controller":"settings","action":"linkedin"}\', "sitelogin_admin_main_integration", NULL, "1", "0", "5"),
(NULL, "sitelogin_admin_main_integration_facebook", "sitelogin", "Facebook Integration", NULL, \'{"route":"admin_default","module":"sitelogin","controller":"settings","action":"facebook"}\', "sitelogin_admin_main_integration", NULL, "1", "0", "1"),
(NULL, "sitelogin_admin_main_integration_twitter", "sitelogin", "Twitter Integration", NULL, \'{"route":"admin_default","module":"sitelogin","controller":"settings","action":"twitter"}\', "sitelogin_admin_main_integration", NULL, "1", "0", "2"),
(NULL, "sitelogin_admin_main_integration_instagram", "sitelogin", "Instagram Integration", NULL, \'{"route":"admin_default","module":"sitelogin","controller":"settings","action":"instagram"}\', "sitelogin_admin_main_integration", NULL, "1", "0", "4"),
(NULL, "sitelogin_admin_main_integration_yahoo", "sitelogin", "Yahoo Integration", NULL, \'{"route":"admin_default","module":"sitelogin","controller":"settings","action":"yahoo"}\', "sitelogin_admin_main_integration", NULL, "1", "0", "7"),
(NULL, "sitelogin_admin_main_integration_pinterest", "sitelogin", "Pinterest Integration", NULL, \'{"route":"admin_default","module":"sitelogin","controller":"settings","action":"pinterest"}\', "sitelogin_admin_main_integration", NULL, "1", "0", "6"),
(NULL, "sitelogin_admin_main_integration_vk", "sitelogin", "Vkontakte Integration", NULL, \'{"route":"admin_default","module":"sitelogin","controller":"settings","action":"vk"}\', "sitelogin_admin_main_integration", NULL, "1", "0", "10"),
(NULL, "sitelogin_admin_main_integration_outlook", "sitelogin", "Outlook Integration", NULL, \'{"route":"admin_default","module":"sitelogin","controller":"settings","action":"outlook"}\', "sitelogin_admin_main_integration", NULL, "1", "0", "8"),
(NULL, "sitelogin_admin_main_integration_flickr", "sitelogin", "Flickr Integration", NULL, \'{"route":"admin_default","module":"sitelogin","controller":"settings","action":"flickr"}\', "sitelogin_admin_main_integration", NULL, "1", "0", "9"),
(NULL, "sitelogin_admin_main_integration", "sitelogin", "Social Sites Integration", NULL, \'{"route":"admin_default","module":"sitelogin","controller":"settings","action":"facebook"}\', "sitelogin_admin_main", NULL, "1", "0", "2"),
(NULL, "sitelogin_admin_main_faq_help", "sitelogin", "FAQ", NULL, \'{"route":"admin_default","module":"sitelogin","controller":"settings","action":"faq"}\', "sitelogin_admin_main_faq", NULL, "1", "0", "50"),
(NULL, "sitelogin_admin_main_faq_app", "sitelogin", "App Creation", NULL, \'{"route":"admin_default","module":"sitelogin","controller":"settings","action":"appfaq"}\', "sitelogin_admin_main_faq", NULL, "1", "0", "51"),
(NULL, "sitelogin_admin_main_stats", "sitelogin", "Statistics", NULL, \'{"route":"admin_default","module":"sitelogin","controller":"settings","action":"statistics"}\', "sitelogin_admin_main", NULL, "1", "0", "45"),
(NULL, "sitelogin_admin_main_manage", "sitelogin", "Manage Social Sites Services", NULL, \'{\"route\":\"admin_default\",\"module\":\"sitelogin\",\"controller\":\"settings\",\"action\":\"manage\"}\', "sitelogin_admin_main", NULL, "1", "0", "30");
');?>